name: Publish Docker image
on:
  push:
    tags:
      - '*'
  workflow_dispatch: 
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
        working-directory: .  
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - 
        name: Docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }
      - 
        name: Docker build
        run: |
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}:${{steps.tag.outputs.tag}} .
          if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }
      -
        name: Docker push
        run: |
          docker image push ${{ secrets.DOCKER_REPOSITORY}}:${{steps.tag.outputs.tag}}
          if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }
      -
        name: Docker logout
        run: |
          docker logout
          if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }
  docker-readme:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          readme-filepath: ./README-Dockerhub.md